//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginTableau.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public long id_logeo { get; set; }
        public Nullable<System.DateTime> fechainiciosesion { get; set; }
        public Nullable<System.DateTime> fechafinsesion { get; set; }
        public Nullable<long> id_usuario { get; set; }
    
        public virtual UsuarioTableau UsuarioTableau { get; set; }
    }
}
